---
title: "Data processing"
author: "Lisa Fisher"
date: "3/24/2021"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(gender)
library(devtools)
library(genderdata)

```


```{r}
install.packages("genderdata", repos = "https://dev.ropensci.org", type = "source")
install_genderdata_package()

devtools::install_github("ropensci/genderdata")
```


```{r}
# Read in Data
coaches <- read_csv("data/coaches.csv")

head(coaches)
View(coaches)

coaches <- coaches %>%
separate(Name, c("lastName", "firstName"), sep = ", ", extra = "merge") %>%
  mutate(firstName = substr(firstName, 1, nchar(firstName)-1))



class(coaches$firstName) 

coaches$firstName
```


```{r}
# Testing gender library

names <- gender(coaches$firstName, method = c("ssa", "ipums", "napp", "kantrowitz", "genderize", "demo"))
View(names)

names <- names %>%
  distinct(name, proportion_male, proportion_female, gender)





coaches <- coaches %>%
  mutate(gender = ifelse(is.null(gender(firstName, method = c("ssa", "ipums", "napp", "kantrowitz", "genderize", "demo"), years = 2012)[1,4]), "none", gender(firstName, method = c("ssa", "ipums", "napp", "kantrowitz", "genderize", "demo"), years = 2012)[1,4]))


gender(coaches$firstName[], method = c("ssa", "ipums", "napp", "kantrowitz", "genderize", "demo"), years = 2012)[1,4]


gender_df(coaches, 
          method = c("ssa", "ipums", "napp", "kantrowitz", "genderize", "demo"), 
          name_col = "firstName")




```




```{r}
names <- gender(coaches$firstName, method = c("ssa", "ipums", "napp", "kantrowitz", "genderize", "demo"))
View(names)

names <- names %>%
  distinct(name, proportion_male, proportion_female, gender)

names$name

coaches <- coaches %>%
  full_join(names, coaches, by = c("firstName" = "name"))




```

